---
homebrew_taps:
  - homebrew/cask-drivers

homebrew_casks:
  - bitwarden
  - dropbox
  - firefox
  - logitech-options
  - microsoft-office
  - moom
  - obsidian
  - slack
  - sonos
  - spotify
  - synology-drive
  - visual-studio-code

mas_apps:
  - name: 2Do
    id: 477670270
  - name: Disk Speed Test
    id: 425264550
