---
- name: Configure git aliases
  command: git config --global alias.{{ item.name }} '{{ item.value }}'
  loop: "{{ git_aliases }}"

- name: Configure global gitignores
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: "{{ lookup('env', 'HOME') }}/.gitignore_global"

- name: Copy gitignore_global
  ansible.builtin.copy:
    src: gitignore_global
    dest: ~/.gitignore_global
    mode: "0644"
