---
- name: Add homebrew taps
  community.general.homebrew_tap:
    name: "{{ homebrew_taps }}"
    state: present

- name: Install homebrew casks
  community.general.homebrew_cask:
    name: "{{ homebrew_casks }}"
    state: latest

- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
    state: latest
