---
- name: Add homebrew taps
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install iterm2
  community.general.homebrew_cask:
    name: "{{ iterm2_casks }}"
    state: present

- name: Install fonts
  community.general.homebrew_cask:
    name: "{{ iterm2_fonts }}"
    state: present

- name: Check if ohmyzsh is already installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_result

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_result.stat.exists

- name: Check if powerlevel10k is already installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
  register: p10k_result

- name: Install powerlevel10k theme
  shell: git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k
  when: not p10k_result.stat.exists

- name: Update zshrc config
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0755
    backup: yes
