---
- name: Add homebrew taps
  community.general.homebrew_tap:
    name: homebrew/cask-fonts
    state: present

- name: Install iterm2
  community.general.homebrew_cask:
    name: iterm2
    state: present

- name: Install fonts
  community.general.homebrew_cask:
    name: "{{ iterm2_fonts }}"
    state: present

- name: Check if ohmyzsh is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: ohmyzsh_result

- name: Install ohmyzsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh_result.stat.exists

- name: Check if powerlevel10k is already installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
  register: p10k_result

- name: Install powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  when: not p10k_result.stat.exists

- name: Install fzf
  community.general.homebrew:
    name: fzf
    state: present

- name: Get fzf location
  ansible.builtin.command: brew --prefix fzf
  register: fzfprefix_output
  changed_when: false

- name: Configure keybindings and fuzzy completion
  ansible.builtin.template:
    src: fzf.zsh.j2
    dest: "{{ ansible_env.HOME }}/.fzf.zsh"
    mode: 0755
    backup: true
  vars:
    fzf_path: "{{ fzfprefix_output.stdout }}"

- name: Install additional packages required by plugins
  community.general.homebrew:
    name: "{{ zsh_packages }}"

- name: Update zshrc config
  ansible.builtin.template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0755
    backup: true

- name: Install devbox script
  ansible.builtin.template:
    src: devbox.zsh.j2
    dest: "{{ ansible_env.HOME }}/.devbox.zsh"
    mode: 0755
    backup: true

- name: Install kubectl aliases
  ansible.builtin.template:
    src: kubectl.zsh.j2
    dest: "{{ ansible_env.HOME }}/.kubectl.zsh"
    mode: 0755
    backup: true
