---
- name: Ensure config.d exists in user .ssh folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.ssh/{{ ssh_config_include_dir }}/"
    state: directory
    mode: "0755"

- name: Generate ssh config file
  ansible.builtin.template:
    src: config.j2
    dest: "{{ ansible_env.HOME }}/.ssh/config"
    mode: 0644

- name: Copy each file over that matches the given pattern
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/config.d/{{ item | basename }}"
    state: link
  with_fileglob:
    - "{{ ssh_config_shared_dir }}/*"
